export const SET_PHOTO_ID = 'SET_ALBUM_ID'
export const FETCH_PHOTOS_REQUEST = 'FETCH_PHOTOS_REQUEST'
export const FETCH_PHOTOS_SUCCESS = 'FETCH_PHOTOS_SUCCESS'
export const FETCH_PHOTOS_FAILURE = 'FETCH_PHOTOS_FAILURE'